# Generated by Django 6.0.2 on 2026-03-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='user',
            new_name='owner',
        ),
    ]
